
"use client";

import { useState } from 'react';
import { useUser, useFirestore, useCollection, useMemoFirebase, setDocumentNonBlocking, updateDocumentNonBlocking } from '@/firebase';
import { collection, doc, serverTimestamp, query, where } from 'firebase/firestore';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { format } from "date-fns";
import { Calendar as CalendarIcon, FileCheck, MapPin, Plus, Clock, Loader2, FileText, Download, CheckCircle2, ClipboardList } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import { generateInspectionReport } from "@/ai/flows/generate-inspection-report";
import { jsPDF } from "jspdf";

export default function InspectionsPage() {
  const { user } = useUser();
  const db = useFirestore();
  const { toast } = useToast();

  const propertiesQuery = useMemoFirebase(() => {
    if (!db || !user) return null;
    return query(
      collection(db, 'properties'),
      where('landlordId', '==', user.uid)
    );
  }, [db, user]);

  const { data: properties, isLoading: isPropLoading } = useCollection(propertiesQuery);

  const inspectionsQuery = useMemoFirebase(() => {
    if (!db || !user) return null;
    return query(
      collection(db, 'inspections'),
      where('landlordId', '==', user.uid)
    );
  }, [db, user]);

  const { data: inspections, isLoading: isInspLoading } = useCollection(inspectionsQuery);

  const [date, setDate] = useState<Date>();
  const [selectedPropertyId, setSelectedPropertyId] = useState('');
  
  // Conduct Inspection State
  const [activeInspection, setActiveInspection] = useState<any>(null);
  const [findings, setFindings] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleSchedule = () => {
    if (!user || !db || !selectedPropertyId || !date) return;

    const inspectionId = doc(collection(db, 'dummy')).id;
    const inspectionRef = doc(db, 'inspections', inspectionId);

    setDocumentNonBlocking(inspectionRef, {
      id: inspectionId,
      propertyId: selectedPropertyId,
      landlordId: user.uid,
      scheduledDate: date.toISOString(),
      status: 'scheduled',
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    }, { merge: true });

    toast({ title: "Inspection Scheduled", description: `New inspection set for ${format(date, 'PPP')}` });
    setSelectedPropertyId('');
    setDate(undefined);
  };

  const handleConduct = async () => {
    if (!db || !activeInspection || !findings) return;

    setIsGenerating(true);
    const property = properties?.find(p => p.id === activeInspection.propertyId);

    try {
      const aiReport = await generateInspectionReport({
        propertyAddress: property?.addressLine1 || 'Property',
        findings: findings
      });

      const inspectionRef = doc(db, 'inspections', activeInspection.id);
      updateDocumentNonBlocking(inspectionRef, {
        status: 'completed',
        findings: findings,
        summary: aiReport.summary,
        priorityItems: aiReport.priorityItems,
        healthScore: aiReport.healthScore,
        conductedDate: new Date().toISOString(),
        updatedAt: serverTimestamp(),
      });

      toast({ title: "Inspection Completed", description: "Professional report generated by AI." });
      setActiveInspection(null);
      setFindings('');
    } catch (error) {
      toast({ variant: "destructive", title: "Reporting Failed", description: "AI could not generate summary at this time." });
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPDF = (inspection: any) => {
    const property = properties?.find(p => p.id === inspection.propertyId);
    const doc = new jsPDF();
    
    doc.setFontSize(22);
    doc.text("Property Inspection Report", 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Property: ${property?.addressLine1 || 'Unknown'}`, 20, 35);
    doc.text(`Date: ${format(new Date(inspection.conductedDate), 'PPP')}`, 20, 42);
    doc.text(`Condition Score: ${inspection.healthScore}/100`, 20, 49);
    
    doc.setFontSize(14);
    doc.text("AI Summary", 20, 65);
    doc.setFontSize(10);
    const splitSummary = doc.splitTextToSize(inspection.summary, 170);
    doc.text(splitSummary, 20, 72);
    
    let y = 72 + (splitSummary.length * 5) + 10;
    doc.setFontSize(14);
    doc.text("Priority Maintenance", 20, y);
    doc.setFontSize(10);
    y += 7;
    inspection.priorityItems.forEach((item: string, i: number) => {
      doc.text(`- ${item}`, 20, y + (i * 6));
    });
    
    doc.save(`Inspection_${property?.addressLine1}_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
  };

  if (isPropLoading || isInspLoading) return <div className="flex h-[60vh] items-center justify-center"><Loader2 className="animate-spin text-primary" /></div>;

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 text-left">
        <div>
          <h1 className="text-3xl font-headline font-bold text-primary mb-2">Inspections & Compliance</h1>
          <p className="text-muted-foreground font-medium">Maintain property standards with structured reporting.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <Card className="lg:col-span-1 border-none shadow-sm h-fit">
          <CardHeader>
            <CardTitle className="text-xl">Plan Inspection</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label className="text-xs uppercase font-bold text-muted-foreground">Select Asset</Label>
              <select 
                className="flex h-11 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm"
                value={selectedPropertyId}
                onChange={(e) => setSelectedPropertyId(e.target.value)}
              >
                <option value="">Choose a property...</option>
                {properties?.map(p => <option key={p.id} value={p.id}>{p.addressLine1}</option>)}
              </select>
            </div>
            <div className="space-y-2">
              <Label className="text-xs uppercase font-bold text-muted-foreground">Preferred Date</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant={"outline"}
                    className={cn(
                      "w-full justify-start text-left font-normal h-11 rounded-xl",
                      !date && "text-muted-foreground"
                    )}
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {date ? format(date, "PPP") : <span>Pick a date</span>}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0 rounded-2xl overflow-hidden">
                  <Calendar
                    mode="single"
                    selected={date}
                    onSelect={setDate}
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
            </div>
            <Button className="w-full rounded-xl h-11 font-bold" onClick={handleSchedule} disabled={!date || !selectedPropertyId}>
              Confirm Schedule
            </Button>
          </CardContent>
        </Card>

        <div className="lg:col-span-2 space-y-6">
          <h3 className="text-xl font-bold font-headline flex items-center">
            <ClipboardList className="w-5 h-5 mr-2 text-primary" />
            Inspection Register
          </h3>
          
          <div className="grid gap-4">
            {!inspections || inspections.length === 0 ? (
              <div className="py-20 text-center bg-muted/20 rounded-2xl border-2 border-dashed border-primary/10">
                <p className="text-muted-foreground font-medium">No inspections currently scheduled.</p>
              </div>
            ) : (
              inspections
                .slice()
                .sort((a, b) => new Date(b.scheduledDate).getTime() - new Date(a.scheduledDate).getTime())
                .map((inspection) => (
                  <Card key={inspection.id} className="border-none shadow-sm overflow-hidden group">
                    <CardContent className="p-6">
                      <div className="flex flex-col md:flex-row gap-6">
                        <div className="bg-primary/5 p-4 rounded-2xl flex flex-col items-center justify-center text-primary min-w-[100px] h-fit">
                          <span className="text-xs font-bold uppercase">
                            {format(new Date(inspection.scheduledDate), 'MMM')}
                          </span>
                          <span className="text-3xl font-bold">
                            {format(new Date(inspection.scheduledDate), 'dd')}
                          </span>
                        </div>
                        <div className="flex-1 space-y-3">
                          <div className="flex items-center justify-between">
                            <Badge variant={inspection.status === 'completed' ? 'secondary' : 'default'} className="uppercase font-bold text-[10px]">
                              {inspection.status}
                            </Badge>
                            {inspection.status === 'completed' && (
                              <Button variant="outline" size="sm" onClick={() => downloadPDF(inspection)} className="rounded-lg h-8 text-primary border-primary/20">
                                <Download className="w-3 h-3 mr-2" /> Download PDF
                              </Button>
                            )}
                          </div>
                          <div className="text-left">
                            <h4 className="text-lg font-bold font-headline">
                              {properties?.find(p => p.id === inspection.propertyId)?.addressLine1 || 'Property Asset'}
                            </h4>
                            <p className="text-sm text-muted-foreground flex items-center mt-1">
                              <MapPin className="w-4 h-4 mr-1 text-primary/40" /> {properties?.find(p => p.id === inspection.propertyId)?.zipCode || 'No postcode'}
                            </p>
                          </div>
                          
                          {inspection.status === 'scheduled' && (
                            <Dialog open={activeInspection?.id === inspection.id} onOpenChange={(open) => !open && setActiveInspection(null)}>
                              <DialogTrigger asChild>
                                <Button className="w-full md:w-auto rounded-xl bg-accent hover:bg-accent/90 font-bold" onClick={() => setActiveInspection(inspection)}>
                                  Conduct Inspection
                                </Button>
                              </DialogTrigger>
                              <DialogContent className="sm:max-w-[500px] rounded-2xl">
                                <DialogHeader>
                                  <DialogTitle className="text-xl font-headline font-bold">Inspection Findings</DialogTitle>
                                  <DialogDescription>Record the property condition and required actions.</DialogDescription>
                                </DialogHeader>
                                <div className="space-y-4 py-4">
                                  <div className="space-y-2">
                                    <Label className="font-bold text-xs uppercase text-primary/60">Observations & Notes</Label>
                                    <Textarea 
                                      placeholder="e.g. Living room carpet has minor stains. Kitchen appliances in good order. Small leak found under master sink." 
                                      className="min-h-[150px] rounded-xl"
                                      value={findings}
                                      onChange={(e) => setFindings(e.target.value)}
                                    />
                                  </div>
                                </div>
                                <DialogFooter>
                                  <Button className="w-full rounded-xl h-11 font-bold" onClick={handleConduct} disabled={!findings || isGenerating}>
                                    {isGenerating ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Analyzing...</> : <><CheckCircle2 className="w-4 h-4 mr-2" /> Complete & Generate Report</>}
                                  </Button>
                                </DialogFooter>
                              </DialogContent>
                            </Dialog>
                          )}

                          {inspection.summary && (
                            <div className="p-4 bg-muted/40 rounded-xl border border-primary/5 mt-4 text-left">
                              <p className="text-[10px] font-bold text-primary uppercase mb-2">AI Summary Findings</p>
                              <p className="text-sm text-muted-foreground italic leading-relaxed">{inspection.summary}</p>
                            </div>
                          )}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
